website/application/__init__.py
from flask import Flask

def create_app():
    '''Construct the core application'''
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object('config.Config')
    with app.app_context():
        from .views import view
        app.register_blueprint(view)
        return app

website/application/views.py
from flask import Flask, Blueprint, render_template, request, session, url_for, redirect, flash, jsonify

view = Blueprint("views", __name__)

# GLOBAL CONSTANTS

NAME_KEY = 'name'

# VIEWS

@view.route("/login", methods=["POST", "GET"])
def login():
    """
    displays main login page and handles saving name in session
    :return: None
    """
    if request.method == "POST":
        name = request.form.get("inputName")
        if len(name) >= 2:
            session[NAME_KEY] = name
            flash(f"You were successfully logged in as {name}.")
            return redirect(url_for("views.home"))
        else:
            flash(f"Your name must be longer than one character.")
    return render_template("login.html", **{"session": session})


@view.route("/", methods=["POST", "GET"])
@view.route("/home", methods=["POST", "GET"])
def home():
    """displays home page if logged in
    :return None
    """
    if NAME_KEY not in session:
        return redirect(url_for("views.login"))  
    return render_template("index.html", **{"session": session})

@view.route("/history")
def history():
    return render_template("history.html", **{"session": session})

@view.route('/logout')
def logout():
    """
    logs the user out by removing their name from the session
    :return: None
    """
    session.pop(NAME_KEY, None)
    flash("You were logged out.")
    return redirect(url_for("views.login"))

@view.route('/get_name')
def get_name():
    """
    :return: a json object storing the name of the logged-in user
    """
    data = {"name": ""}
    if NAME_KEY in session:
        data = {"name": session[NAME_KEY]}
    return jsonify(data)

website/application/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width", initial-scale=1, shrink-to-fit="no">
        <link rel="stylesheet" type="text/css" href="../static/css/base.css">
        {% block css %} {% endblock %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.2.0/socket.io.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Poppins:ital,wght@0,500;0,600;0,700;1,400&family=Ubuntu:wght@400;500;700&display=swap" rel="stylesheet">
    </head> 
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand brand" href="#">ChatApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse navbar-nav item d-inline-flex">
                    <a class="nav-item nav-link" href="{{ url_for('views.home') }}">Chat</a>
                    <a class=" nav-item nav-link" href="{{ url_for('views.history') }}">History</a>
                    {% block log %} {% endblock %}
                </div>
            </div>
        </nav>

        {% block messages %}
            {% with messages = get_flashed_messages() %}
                {% for msg in messages %}
                    <div class="alert alert-dark p-2" role="alert">
                    {{ msg }}
                    </div>
                {% endfor %}
            {% endwith %}
        {% endblock %}

        {% block content %} {% endblock %}  

        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top fixed-bottom">
            <div class="col-md-4 d-flex align-items-center">
              <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
              </a>
              <span class="text-muted">© 2023 ChatApp</span>
            </div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/index.js') }}"></script>
    </body>
</html>

website/application/templates/history.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>It's Matthew</title>
        <link rel="stylesheet" href="../static/css/history.css"></link>
    </head>

    <body>
        <div class="parent" style="background-color: beige; border: 2px; border: solid; border-color: black;">
            My Div
            <p class="first" style="background-color: gray;">One</p>
            <p class="second" style="background-color: blue;">Two</p>
            <p class="third" style="background-color: darkgreen;">Three</p>
        </div>
    </body>
</html>

website/application/templates/index.html
{% extends "base.html" %}

{% block log %}
<a class="nav-item nav-link" href="{{ url_for('views.logout') }}">Logout</a>
{% endblock %}  

{% block css %}
<link rel="stylesheet" type="text/css" href="../static/css/index.css">
{% endblock %}

{% block content %}

<div class="row" style="padding-top:10px;" >
    <div class="col"><hr></div>
    <div class="col-auto"><p class="h3" text-align="center">Start Chatting</p></div>
    <div class="col"><hr></div>
</div>

<div class="container">
    <div id="messages" class="overflow-auto msgs">
        <!-- For js message insertion-->
    </div>
    <form id="msgForm" action="" method="POST" class="send-layout">
        <div class="input-group mb-3">
              <input type="text" class="form-control" placeholder="Message" aria-label="Message" id="msg">
              <div class="input-group-append">
                <button class="btn btn-success" type="submit" id="sendBtn">Send</button>
              </div>
        </div>
    </form>
</div>

{% endblock %}  

website/application/templates/login.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" type="text/css" href="../static/css/login.css">
{% endblock %}

{% block log %}
<a class="nav-item nav-link" href="{{ url_for('views.login') }}">Login</a>
{% endblock %}

{% block content %} 

<div class="login-page">
    <form class="login-form shadow p-3 mb-5 pb-3 pt-3 bg-white rounded" action="#" method="POST">
        <input type="text" class="form-control" name="inputName" id="inputName" placeholder="Your Name" aria-label="Username" aria-describedby="basic-addon1">
        <button type="submit" class="btn btn-success mb-2 form-control">Submit</button>
    </form>
</div>
{% endblock %}